### ISSUE TITLE
Animation Banner Sample

### ISSUE THREAD

**Issue by lucemia** [livingbio/lottie-web#8]
## Problem

利用 Lottie 做一個 "漂亮的動態類影片 Banner Ad" (看起來像影片一樣好，但是是 h5)，
讓我們有獨特的廣告格式，這個格式有幾個好處:

1. 比起一般的 h5 廣告，看起來漂亮不死板
2. 比起影片，使用的流量比較少
3. 可以動態調整內容 (e.g. 每個人看到的照片都不一樣)

Template Sample: https://drive.google.com/open?id=10DE1REussmp9aCAsUMPzYJqLnKQIV_qF

但這個 Template 與享狩不同，我們從 StoryBlocks 下載的素材有設定 PlaceHolder 
data.json 中的相關結構複雜很多

## Goal

找出將素材塞入 data.json 的正確方式，做出一個動態 Banner
由於 Lottie-web 支持的 Effect 有限，如果轉出來的差一些沒關係

**Comment by lucemia** [comment]
StoryBlocks 下載的 Template，素材部分是設定成 空白的 Comp 

> Precomposing is the process of packaging a series of layers into a new composition in After Effects. In a way it's the same as grouping layers in Photoshop. By grouping these layers together you can add animation, effects, or masks that will then be applied to all of the layers within.

<img width="926" alt="截圖 2020-04-10 下午10 57 15" src="https://user-images.githubusercontent.com/432851/79000155-b28e7e00-7b7e-11ea-8c02-edae45ff6132.png">
<img width="779" alt="截圖 2020-04-10 下午10 57 24" src="https://user-images.githubusercontent.com/432851/79000165-b6ba9b80-7b7e-11ea-8c61-8ee424020750.png">

**Comment by lucemia** [comment]
```
 "assets": {
      "title": "Assets",
      "description": "source items that can be used in multiple places. Comps and Images for now.",
      "items": {
        "oneOf": [
          {
            "$ref": "#/sources/image"
          },
          {
            "$ref": "#/sources/precomp"
          }
        ],
        "type": "object"
      },
      "type": "array"
    },
```

comp_58  是 precomp

**Comment by lucemia** [comment]
享狩的 template 是直接使用圖片

<img width="747" alt="截圖 2020-04-10 下午11 35 44" src="https://user-images.githubusercontent.com/432851/79002891-0780c300-7b84-11ea-80f3-c2b0ad0557a3.png">

**Comment by vickyliin** [comment]
**放入素材**
進 AE 選到 01. EDIT -> SHOT 然後把照片拉進對應的 shot
之後再輸出成 bodymovin 資料就可以了

**修改素材**
輸出 bodymovin 後修改 assets

**其他問題**
- 這個 template 連顏色都是用 effect，所以連顏色也沒有～
- 只要給影片都顯示不出來，不知道是 template 問題還是 lottie 支援問題


如果真的要用 lottie 做漂亮的 h5 banner 的話，
最可行的做法應該是請會用 AE 做影片的人**只**用我們支援的特效客制 template，
工程師再修改 template 裡面的資料～

更進一步就是我們 fork bodymovin 的 AE plugin，讓設定資料 slot 這件事可以在 AE plugin 裡完成，
直接從 plugin 輸出可以丟資料的網頁

**Comment by lucemia** [comment]
> * 這個 template 連顏色都是用 effect，所以連顏色也沒有～
> * 只要給影片都顯示不出來，不知道是 template 問題還是 lottie 支援問題

lottie 支援問題，原因是 https://github.com/livingbio/lottie-web/issues/7

**Comment by lucemia** [comment]
可以套版了
https://storage.googleapis.com/livingbio-tmp/banner/index.html

現在顏色跑不出來反而效果還可以，那個粉紅色很糟...
